# Compile mizuRoute on personal computer
# export variables are used in the makefile. 

#---------------------------------
# Specify settings
#---------------------------------

# --- Location of source code
# Find the path to the source code in 'control_active.txt'
dest_line=$(grep -m 1 "^install_path_mizuroute" ../0_config_files/control_active.txt)  # full settings line
mizu_path=$(echo ${dest_line##*|})   # removing the leading text up to '|' 
mizu_path=$(echo ${mizu_path%%#*})  # removing the trailing comments, if any are present

# Specify the default path if needed
if [ "$mizu_path" = "default" ]; then
  
 # Get the root path and append appropriate install directories
 root_line=$(grep -m 1 "^root_path" ../0_config_files/control_active.txt)
 root_path=$(echo ${root_line##*|}) 
 root_path=$(echo ${root_path%%#*}) 
 mizu_path="${root_path}/installs/mizuRoute/route/" # note: NEEDS a trailing '/'

# With custom path, we still need to specify the /route directory for compilation
else 
 mizu_path="${mizu_path}/route/" # note: NEEDS a trailing '/'
fi

# Specify home directory of mizuroute/build
#export 
F_MASTER=$mizu_path


# --- Specify a name for the executable 
# Find the desired executable name in 'control_active.txt'
exe_line=$(grep -m 1 "^exe_name_mizuroute" ../0_config_files/control_active.txt) 
mizu_exe=$(echo ${exe_line##*|}) 
mizu_exe=$(echo ${mizu_exe%%#*}) 
#export 
EXE=$mizu_exe


# --- Compiler settings 
# Compiler (used in selection statements inside Makefile)
FC=gnu
FC_EXE='mpif90'  # For gnu compilers, this is usually 'gfortran'

# --- Library settings
# Instead of modules, define your NetCDF path directly
NCDF_PATH="/home/dlhogan/miniconda3/envs/mtnhydropysumma/"  # CHANGE THIS to your actual path

# Specify if OpenMP is to be used
isOpenMP="no"

# Compiler flags
if [ $isOpenMP = "yes" ]; then
  FLAGS_OMP="-fopenmp"
fi
FLAGS="-O3 -ffree-line-length-none -fmax-errors=0 ${FLAGS_OMP}"

# Optional mode: fast / debug / profile
# --- Define optional setting
# fast:      Enables optimizations
# debug:     Minimum debug options, still
# profile:   Enables profiling
#export MODE=debug 
                 
				 
#---------------------------------
# Print the settings
#---------------------------------
echo 'build directory: ' $F_MASTER
echo 'executable name: ' $EXE
echo 'compiler name:   ' $FC
echo 'compiler .exe:   ' $FC_EXE
echo 'netcdf path:     ' $NCDF_PATH
echo 'isOpenMP:        ' $isOpenMP
echo 'compile mode:    ' $MODE
echo 'compiler flags:  ' $FLAGS
echo # empty line				 


#---------------------------------
# Compile
#---------------------------------
make -f ${F_MASTER}/build/Makefile FC=$FC FC_EXE=$FC_EXE EXE=$EXE MODE=$MODE isOpenMP=$isOpenMP F_MASTER=$F_MASTER NCDF_PATH=$NCDF_PATH FLAGS="$FLAGS"


#---------------------------------
# Code provenance
#---------------------------------
# Generates a basic log file in the domain folder and copies the control file and itself there.
# Make a log directory if it doesn't exist
log_path="${mizu_path}/_workflow_log"
mkdir -p $log_path

# Log filename
today=`date '+%F'`
log_file="${today}_compile_log.txt"

# Make the log
this_file='2b_compile_mizuroute.sh'
echo "Log generated by ${this_file} on `date '+%F %H:%M:%S'`"  > $log_path/$log_file # 1st line, store in new file
echo 'Compiled mizuRoute into parent directory' >> $log_path/$log_file # 2nd line, append to existing file

# Copy this file to log directory
cp $this_file $log_path